[tool.black]
line-length = 88
target-version = ["py311"]
exclude = "venv|migrations"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]  # Errores de sintaxis y mejoras en imports
ignore = ["E501"]  # Evitar warnings por líneas largas
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
