"""cascade delete clientes_corredores

Revision ID: 98f77e2ce8c3
Revises: fix_corredor_sequences
Create Date: 2025-05-01 17:33:12.112499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f77e2ce8c3'
down_revision: Union[str, None] = 'fix_corredor_sequences'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clientes_corredores_cliente_id_fkey', 'clientes_corredores', type_='foreignkey')
    op.create_foreign_key(None, 'clientes_corredores', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes_corredores', type_='foreignkey')
    op.create_foreign_key('clientes_corredores_cliente_id_fkey', 'clientes_corredores', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
