"""Initial migration

Revision ID: initial
Revises: 
Create Date: 2025-02-05 21:25:06.488805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aseguradoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pagina_web', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_aseguradoras_id'), 'aseguradoras', ['id'], unique=False)
    op.create_table('corredores',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=30), nullable=True),
    sa.Column('apellidos', sa.String(length=30), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=70), nullable=False),
    sa.Column('localidad', sa.String(length=15), nullable=False),
    sa.Column('telefonos', sa.String(length=20), nullable=True),
    sa.Column('movil', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=40), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('especializacion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('numero'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('monedas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_monedas_id'), 'monedas', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('tipos_de_seguros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('cobertura', sa.Text(), nullable=False),
    sa.Column('vigencia_default', sa.Integer(), nullable=True),
    sa.Column('aseguradora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aseguradora_id'], ['aseguradoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('comision_porcentaje', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('corredor_numero', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corredor_numero'], ['corredores.numero'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_cliente', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('telefonos', sa.String(length=100), nullable=False),
    sa.Column('movil', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('modificado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_mail'), 'clientes', ['mail'], unique=True)
    op.create_index(op.f('ix_clientes_numero_cliente'), 'clientes', ['numero_cliente'], unique=True)
    op.create_index(op.f('ix_clientes_numero_documento'), 'clientes', ['numero_documento'], unique=True)
    op.create_table('clientes_corredores',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('corredor_numero', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['corredor_numero'], ['corredores.numero'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'corredor_numero')
    )
    op.create_table('movimientos_vigencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('corredor_id', sa.Integer(), nullable=True),
    sa.Column('tipo_seguro_id', sa.Integer(), nullable=False),
    sa.Column('carpeta', sa.String(length=100), nullable=True),
    sa.Column('numero_poliza', sa.String(length=100), nullable=False),
    sa.Column('endoso', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('estado_poliza', sa.String(length=20), nullable=True),
    sa.Column('forma_pago', sa.String(length=20), nullable=True),
    sa.Column('tipo_endoso', sa.String(length=50), nullable=True),
    sa.Column('moneda_id', sa.Integer(), nullable=True),
    sa.Column('suma_asegurada', sa.Float(), nullable=False),
    sa.Column('prima', sa.Float(), nullable=False),
    sa.Column('comision', sa.Float(), nullable=True),
    sa.Column('cuotas', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['corredor_id'], ['corredores.numero'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['monedas.id'], ),
    sa.ForeignKeyConstraint(['tipo_seguro_id'], ['tipos_de_seguros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_poliza')
    )
    op.create_index(op.f('ix_movimientos_vigencias_id'), 'movimientos_vigencias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_vigencias_id'), table_name='movimientos_vigencias')
    op.drop_table('movimientos_vigencias')
    op.drop_table('clientes_corredores')
    op.drop_index(op.f('ix_clientes_numero_documento'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_numero_cliente'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_mail'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_de_seguros')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_monedas_id'), table_name='monedas')
    op.drop_table('monedas')
    op.drop_table('corredores')
    op.drop_index(op.f('ix_aseguradoras_id'), table_name='aseguradoras')
    op.drop_table('aseguradoras')
    # ### end Alembic commands ###
